#ifndef TENSORFLOW_LITE_DELEGATES_GPU_GL_PORTABLE_OPENGL_H_
#define TENSORFLOW_LITE_DELEGATES_GPU_GL_PORTABLE_OPENGL_H_


//Will add more later e.g. GLU, GLAD, etc

#include <GL/glew.h>

#endif  // TENSORFLOW_LITE_DELEGATES_GPU_GL_PORTABLE_OPENGL_H_
